# Generated by Django 4.1.7 on 2023-03-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SpamReportModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_id", models.EmailField(default="", max_length=254, null=True)),
                ("phone_no", models.IntegerField(default=0, null=True)),
                ("spams_reported", models.IntegerField(default=0)),
            ],
        ),
    ]
